# Punt a la bola

In [1]:
import h5py
import pandas as pd
import numpy as np
import os
import random

Per representar un vector de velocitat en una esfera matemàticament, pots seguir aquests passos:

1. **Normalitzar el vector** per obtenir un vector unitari que representi la direcció del moviment.
2. **Convertir el vector unitari a coordenades esfèriques** per determinar el punt en la superfície de l'esfera unitària.

## Coordenades

In [2]:
h5_file_coord =  f'/home/jovyan/workspace/Desktop/wa/3d/no_t/outputs_3d_no_t_ample-moltsanys-3650-60anys-velocity_field_strain_rate_tensor/lag-5.h5'


with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name to store coord
    dataset_name = f'np_array_5'

    for key in file.keys():
        # create a string with the name of the var, and assign numpy value from h5
        globals()[dataset_name] = file[key][:] 

np_array_5[0]  

coordinates = np_array_5[0]  
coordinates

array([1404.07337971, 4997.74705993, -150.59059709])

## Velocity gradient

In [3]:
h5_file_coord =  f'/home/jovyan/workspace/Desktop/wa/3d/no_t/outputs_3d_no_t_ample-moltsanys-3650-60anys-velocity_field_strain_rate_tensor/lag_velocitygradient-5.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
dataset_name[0]

array([ 5.5735467e-16,  9.4837845e-17, -2.0862744e-16, -7.3534170e-16,
       -1.3298003e-16, -1.9176785e-17,  1.4636365e-15,  1.6653539e-16,
        1.5577066e-16], dtype=float32)

In [4]:
velocity_gradient = dataset_name[0]
velocity_gradient

array([ 5.5735467e-16,  9.4837845e-17, -2.0862744e-16, -7.3534170e-16,
       -1.3298003e-16, -1.9176785e-17,  1.4636365e-15,  1.6653539e-16,
        1.5577066e-16], dtype=float32)

## to df

In [5]:
import pandas as pd
import numpy as np

In [6]:
# Create the DataFrame
data = {
    'x': [coordinates[0]],
    'y': [coordinates[1]],
    'z': [coordinates[2]],
    'vg00': [velocity_gradient[0]],
    'vg01': [velocity_gradient[1]],
    'vg02': [velocity_gradient[2]],
    'vg10': [velocity_gradient[3]],
    'vg11': [velocity_gradient[4]],
    'vg12': [velocity_gradient[5]],
    'vg20': [velocity_gradient[6]],
    'vg21': [velocity_gradient[7]],
    'vg22': [velocity_gradient[8]],
}

          
df = pd.DataFrame(data)
df.head()

x           y           z          vg00          vg01  \
0  1404.07338  4997.74706 -150.590597  5.573547e-16  9.483785e-17   

           vg02          vg10          vg11          vg12          vg20  \
0 -2.086274e-16 -7.353417e-16 -1.329800e-16 -1.917678e-17  1.463637e-15   

           vg21          vg22  
0  1.665354e-16  1.557707e-16

In [7]:
df.to_csv('velocity_gradient_data.csv', index=False)

# Velocity field

In [8]:
h5_file_coord =  f'/home/jovyan/workspace/Desktop/wa/3d/no_t/outputs_3d_no_t_ample-moltsanys-3650-60anys-velocity_field_strain_rate_tensor/lag_velocityfield-5.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
dataset_name[0]

array([ 2.4120150e-10, -1.1765236e-10, -1.9461415e-11], dtype=float32)

In [9]:
velocity_field = dataset_name[0]
velocity_field

array([ 2.4120150e-10, -1.1765236e-10, -1.9461415e-11], dtype=float32)

In [10]:
# Create the DataFrame
data = {
    'x': 1500,
    'y': [coordinates[0]],
    'z': [coordinates[2]],
    'vx': [velocity_field[0]],
    'vy': [velocity_field[1]],
    'vz': [velocity_field[2]]
}

          
df = pd.DataFrame(data)
df.head()

x           y           z            vx            vy            vz
0  1500  1404.07338 -150.590597  2.412015e-10 -1.176524e-10 -1.946142e-11

In [11]:
df.to_csv('velocity_vector_data.csv', index=False)

## Strain rate tensor

In [12]:

h5_file_coord =  f'/home/jovyan/workspace/Desktop/wa/3d/no_t/outputs_3d_no_t_ample-moltsanys-3650-60anys-velocity_field_strain_rate_tensor/lag_strainratetensor-5.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
dataset_name[0]

array([ 5.5735467e-16, -1.3298003e-16,  1.5577066e-16, -3.2025191e-16,
        6.2750456e-16,  7.3679307e-17], dtype=float32)

In [13]:
strain_rate = dataset_name[0]
strain_rate

array([ 5.5735467e-16, -1.3298003e-16,  1.5577066e-16, -3.2025191e-16,
        6.2750456e-16,  7.3679307e-17], dtype=float32)

# Exemple part 410

### Coordenades

In [14]:
path = '/home/jovyan/workspace/Desktop/mite_outputs/test_temp_final/my_positions/path/position_410_119.h5'

In [15]:
h5_file_coord =  path

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
coordinates = dataset_name[-1]
coordinates

array([1826.41716366, 1386.32530614, -245.2284218 ])

### Velfield410

In [16]:
pre = '/home/jovyan/workspace/Desktop/mite_outputs/test_temp_final/'

In [17]:
h5_file_coord =  pre+'data/lag_velocityfield-119.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
velocity_field = dataset_name[410]
velocity_field

array([ 7.0898031e-11, -6.3705877e-12, -2.8511722e-11], dtype=float32)

In [18]:
# Create the DataFrame
data = {
    'x': [coordinates[0]],
    'y': [coordinates[1]],
    'z': [coordinates[2]],
    'vx': [velocity_field[0]],
    'vy': [velocity_field[1]],
    'vz': [velocity_field[2]]
}

          
df = pd.DataFrame(data)
df.head()

x            y           z            vx            vy  \
0  1826.417164  1386.325306 -245.228422  7.089803e-11 -6.370588e-12   

             vz  
0 -2.851172e-11

In [19]:
df.to_csv('plot_velvector_arrow.csv', index=False)

1. Open ParaView and Load csv, csv reader, apply

2. Convert Table to Points:

Use the Table To Points filter to set x, y, and z columns.

3. Combine Velocity Components:

Use the Calculator filter to create a vector: `iHat*vx + jHat*vy + kHat*vz` and name it VelocityVector

4. Apply Glyph Filter:
scale factor 500

# Exemple 410 all timestep

In [20]:
pre = '/home/jovyan/workspace/Desktop/mite_outputs/test_temp_final/data/'

In [24]:
prefix = f'lag_velocityfield'
files = os.listdir(pre)
num_files = sum([1 for file in files if file.startswith(prefix)])
print(num_files)

pd.set_option('display.precision', 20)
columns = ['x', 'y', 'z', 'vx', 'vy', 'vz']
df = pd.DataFrame(columns=columns)

# loop by number of files
time = 0
while time < num_files:
    h5_file =  pre + f'lag_velocityfield-{time}.h5'
    with h5py.File(h5_file, 'r') as file:
        vel_field = file[key][410]
    
    #print(vel_field)
        
    h5_file_coord =  pre +  f'lag-{time}.h5'

    with h5py.File(h5_file_coord, 'r') as file:
        # create a variable name for storing strain rate tensor array
        dataset_name = f'np_array_6'

        for key in file.keys():
            dataset_name = file[key][:] 


    coordinates = dataset_name[410]
    x = coordinates[0]
    y = coordinates[1]
    z = coordinates[2]
    vx = vel_field[0]
    vy = vel_field[1]
    vz = vel_field[2]
    new_row = {'x': x, 'y': y, 'z': z, 'vx': vx, 'vy': vy, 'vz': vz}
    df = df.append(new_row, ignore_index=True)
    #print(coordinates)
    
    
    time += 1


120


/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/3939463710.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

In [27]:
df['timestep'] = range(len(df))

In [28]:
df.head()

x                          y  \
0  1466.66666666666674245789  1361.11111111111131322104   
1  1496.08567855159776627261  1360.74805604770790523617   
2  1501.27902768126705268514  1359.46019124250574350299   
3  1505.01456280523552777595  1360.54028135697944890126   
4  1508.31455143778202909743  1361.52287466428674633789   

                          z                      vx                      vy  \
0                    -150.0                     0.0                     0.0   
1  -157.1645904456737810051   0.0000000001732088778 -0.00000000000340018985   
2  -157.7462228572488811551  0.00000000019131118911 -0.00000000000983641727   
3 -158.10538244454306777698  0.00000000009995666794  0.00000000002169284197   
4 -158.43869908638544075075   0.0000000000823843424   0.0000000000268351296   

                       vz  timestep  
0                     0.0         0  
1  0.00000000005868115022         1  
2 -0.00000000001718643457         2  
3  0.00000000007232579119         3  
4 -0.00000000001241361007         4

In [29]:
df.to_csv('velocity_vector_410_alltimesteps.csv', index=False)

## una fletxa per timestep

In [31]:
pre = '/home/jovyan/workspace/Desktop/mite_outputs/test_temp_final/data/'

files = os.listdir(pre)
num_files = sum([1 for file in files if file.startswith(prefix)])
print(num_files)

pd.set_option('display.precision', 20)
columns = ['x', 'y', 'z', 'vx', 'vy', 'vz']
df = pd.DataFrame(columns=columns)

pd.set_option('display.precision', 20)
columns = ['x', 'y', 'z', 'vx', 'vy', 'vz']
df = pd.DataFrame(columns=columns)

# loop by number of files
time = 0
while time < num_files:

    df = pd.DataFrame(columns=columns)

    h5_file =  pre + f'lag_velocityfield-{time}.h5'
    with h5py.File(h5_file, 'r') as file:
        vel_field = file[key][410]
    
    #print(vel_field)
        
    h5_file_coord =  pre +  f'lag-{time}.h5'

    with h5py.File(h5_file_coord, 'r') as file:
        # create a variable name for storing strain rate tensor array
        dataset_name = f'np_array_6'

        for key in file.keys():
            dataset_name = file[key][:] 


    coordinates = dataset_name[410]
    x = coordinates[0]
    y = coordinates[1]
    z = coordinates[2]
    vx = vel_field[0]
    vy = vel_field[1]
    vz = vel_field[2]
    new_row = {'x': x, 'y': y, 'z': z, 'vx': vx, 'vy': vy, 'vz': vz}
    df = df.append(new_row, ignore_index=True)
    #print(coordinates)
    save_path = '/home/jovyan/workspace/Desktop/mite_outputs/test_temp_final/csv/'
    df.to_csv(save_path + f'velocity_vector_410_{time}.csv', index=False)
    
    time += 1

120


/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future versio

/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future versio

/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/225084191.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future versio

## Fletxes de tots els timesteps previs

In [32]:
pre = '/home/jovyan/workspace/Desktop/mite_outputs/test_temp_final/data/'

files = os.listdir(pre)
num_files = sum([1 for file in files if file.startswith(prefix)])
print(num_files)

pd.set_option('display.precision', 20)
columns = ['x', 'y', 'z', 'vx', 'vy', 'vz']
df = pd.DataFrame(columns=columns)


# loop by number of files
time = 0
while time < num_files:

    

    h5_file =  pre + f'lag_velocityfield-{time}.h5'
    with h5py.File(h5_file, 'r') as file:
        vel_field = file[key][410]
    
    #print(vel_field)
        
    h5_file_coord =  pre +  f'lag-{time}.h5'

    with h5py.File(h5_file_coord, 'r') as file:
        # create a variable name for storing strain rate tensor array
        dataset_name = f'np_array_6'

        for key in file.keys():
            coordinates = file[key][410] 

    x = coordinates[0]
    y = coordinates[1]
    z = coordinates[2]
    vx = vel_field[0]
    vy = vel_field[1]
    vz = vel_field[2]
    new_row = {'x': x, 'y': y, 'z': z, 'vx': vx, 'vy': vy, 'vz': vz}
    df = df.append(new_row, ignore_index=True)
    #print(coordinates)
    save_path = '/home/jovyan/workspace/Desktop/mite_outputs/test_temp_final/csv_actual_previ/'
    df.to_csv(save_path + f'velocity_vector_410_{time}.csv', index=False)
    
    time += 1

120


/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_1700/2788059239.py:44: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

In [ ]:
h5_file_coord =  pre+'data/lag_velocityfield-30.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
velocity_field = dataset_name[410]
velocity_field

In [ ]:
h5_file_coord =  pre+'data/lag_velocityfield-31.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
velocity_field = dataset_name[410]
velocity_field

In [ ]:
h5_file_coord =  pre+'data/lag_velocityfield-32.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
velocity_field = dataset_name[410]
velocity_field

In [ ]:
h5_file_coord =  pre+'data/lag_velocityfield-33.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
velocity_field = dataset_name[410]
velocity_field

In [ ]:
h5_file_coord =  pre+'data/lag_velocityfield-34.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
velocity_field = dataset_name[410]
velocity_field

## Dibuixar punt bola from velocity field

In [ ]:
#lag_velocityfield
v = np.array([3.5949249e-10, -1.6759606e-10, -4.3700463e-11], dtype=np.float32)

In [ ]:
# x,y,z
#polt velocitats i angles

In [ ]:
# Normalitzar el vector
v_magnitude = np.linalg.norm(v)
v_norm = v / v_magnitude

In [ ]:
# Components del vector normalitzat
x, y, z = v_norm
x, y

In [ ]:
# Calcular els angles esfèrics
theta = np.arccos(z)
phi = np.arctan2(y, x)
theta, phi

In [ ]:
# Convertir els angles a graus (opcional)
theta_degrees = np.degrees(theta)
phi_degrees = np.degrees(phi)

In [ ]:
print(f"Vector normalitzat: {v_norm}")
print(f"θ (radians): {theta}")
print(f"φ (radians): {phi}")
print(f"θ (graus): {theta_degrees}")
print(f"φ (graus): {phi_degrees}")