In [4]:
import h5py
import pandas as pd
import numpy as np
import os

In [9]:
def draw_tracers(tracers=[1,2,3,4,5,6,7], 
                  data_folder_name='data'):
    #########################################
    """
    Guarda les posicions de la partícula per cada step. 
    Permet dibuixar la traça. 
    Data sources files: 
    - tip{tracer}-{time}.h5
    Final data files: 
    - tip{tracer}-{time}.h5
    - tip{tracer}-{time}.xdmf
    """
    #########################################
    
    # Check if the data folder exists
    if not os.path.exists(data_folder_name):
        raise FileNotFoundError(f"Folder '{data_folder_name}' not found.")
    
    # Check if destination folder exist
    dir_path = './my_positions/path'
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
            
    # count number of times, checking the number that files that starts with prefix
    prefix = f'tip1_velocitygradient'
    files = os.listdir(data_folder_name)
    num_files = sum([1 for file in files if file.startswith(prefix)])
    print(num_files)
    
    #loop by tracer
    for tracer in tracers:
        # loop by number of files
        time = 0
        df = pd.DataFrame(columns=["x", "y", "z"])
        while time < num_files:
            print(f'time: {time}')
            ## COORDINATES ##
            # open Coordinates H5 
            h5_file_coord =  f'./{data_folder_name}/tip{tracer}-{time}.h5'
            if not os.path.exists(h5_file_coord):
                    print(f"Warning: H5 file not found at '{h5_file_coord}'. Skipping this time step.")
                    time += 1
                    continue

            with h5py.File(h5_file_coord, 'r') as file:
                for key in file.keys():
                    np_array = file[key][:][0]
                    #print(np_array)

                custom_keys = ["x", "y", "z"]
                my_dict = dict(zip(custom_keys, np_array))
                df = df.append(my_dict, ignore_index=True)
                #print(df.dtypes)
                df = df.astype(float)
                #print(np_array[0], type(np_array[0]))
                
                filename = f'./my_positions/path/position_{tracer}_{time}.h5'
                with h5py.File(filename, 'w') as h5_file:
                  # Create a dataset within the h5 file
                  dataset = h5_file.create_dataset('data', data=df.values)

            ## XDMF file
            xdmf_text = f"""<?xml version="1.0" ?>
<Xdmf xmlns:xi="http://www.w3.org/2001/XInclude" Version="2.0">
<Domain>
<Grid Name="position_{tracer}_{time}.h5" GridType="Uniform">

    <Time Value="{time} megayear" />

    <Topology Type="POLYVERTEX" NodesPerElement="{time+1}"> </Topology>
        <Geometry Type="XYZ">
            <DataItem Format="HDF" NumberType="Float" Precision="8" Dimensions="{time + 1} 3">position_{tracer}_{time}.h5:/data</DataItem>
        </Geometry>
</Grid>
</Domain>
</Xdmf>
"""
        
            filename_xdmf = f'./my_positions/path/position_{tracer}_{time}.xdmf'
            os.makedirs(os.path.dirname(filename_xdmf), exist_ok=True)
            # Write XDMF content to file
            with open(filename_xdmf, "w") as xdmf_file:
              xdmf_file.write(xdmf_text)


            #########
            time += 1
            #print(df)
        

In [10]:
draw_tracers()

27
time: 0
[1600.  300. -400.]
df append
df post append
x    object
y    object
z    object
dtype: object
1600.0 <class 'numpy.float64'>
pre create h5
time: 1
[1599.80934935  299.19658403 -400.61979348]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1599.8093493496972 <class 'numpy.float64'>
pre create h5
time: 2
[1599.85891837  298.58334712 -401.08164485]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1599.858918371865 <class 'numpy.float64'>
pre create h5
time: 3
[1600.02406289  298.15910309 -401.43832272]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1600.0240628899746 <class 'numpy.float64'>
pre create h5
time: 4
[1600.0050034   297.72017618 -401.83263971]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1600.0050034047674 <class 'numpy.float64'>
pre create h5
time: 5
[1600.28568827  297.28950578 -402.12393235]
df append
df post append
x    float64
y    float64

/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

df post append
x    float64
y    float64
z    float64
dtype: object
1401.2145041494184 <class 'numpy.float64'>
pre create h5
time: 5
[1401.55851811  922.01728923 -404.94892513]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1401.5585181123697 <class 'numpy.float64'>
pre create h5
time: 6
[1401.8311464   922.22423813 -405.85091529]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1401.8311463965306 <class 'numpy.float64'>
pre create h5
time: 7
[1401.77462045  922.38364162 -406.7572482 ]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1401.7746204474245 <class 'numpy.float64'>
pre create h5
time: 8
[1401.86426188  922.54471849 -407.65705451]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1401.8642618753786 <class 'numpy.float64'>
pre create h5
time: 9
[1402.16003677  922.68387154 -408.5851719 ]
df append
df post append
x    float64
y    float64
z    float64
dtype: obje

/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

df post append
x    float64
y    float64
z    float64
dtype: object
1378.902233618197 <class 'numpy.float64'>
pre create h5
time: 12
[1376.56747007  922.58438396 -604.69463401]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1376.5674700651673 <class 'numpy.float64'>
pre create h5
time: 13
[1374.15376083  921.9445948  -605.05028299]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1374.1537608284311 <class 'numpy.float64'>
pre create h5
time: 14
[1372.06932046  920.68405513 -605.44172794]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1372.0693204621552 <class 'numpy.float64'>
pre create h5
time: 15
[1369.59038539  920.31907254 -605.83283349]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1369.5903853869452 <class 'numpy.float64'>
pre create h5
time: 16
[1367.55404532  919.98622342 -606.19312801]
df append
df post append
x    float64
y    float64
z    float64
dtype: 

/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

df post append
x    float64
y    float64
z    float64
dtype: object
1484.6906490577355 <class 'numpy.float64'>
pre create h5
time: 21
[1485.49371871  923.50894319 -155.95146795]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1485.4937187076516 <class 'numpy.float64'>
pre create h5
time: 22
[1486.30983906  923.54299176 -156.18010665]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1486.3098390578314 <class 'numpy.float64'>
pre create h5
time: 23
[1487.11911766  923.59857643 -156.41137397]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1487.119117659051 <class 'numpy.float64'>
pre create h5
time: 24
[1487.94796662  923.63350935 -156.64933112]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1487.9479666151287 <class 'numpy.float64'>
pre create h5
time: 25
[1488.7708829   923.71561951 -156.88809829]
df append
df post append
x    float64
y    float64
z    float64
dtype: 

/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

time: 2
[1468.71189984 1233.31690835 -150.72969543]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1468.7118998377778 <class 'numpy.float64'>
pre create h5
time: 3
[1469.62480208 1233.24192184 -151.01586766]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1469.624802079857 <class 'numpy.float64'>
pre create h5
time: 4
[1470.5021201  1233.13710617 -151.29784223]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1470.5021201043828 <class 'numpy.float64'>
pre create h5
time: 5
[1471.41358618 1233.10637747 -151.59608935]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1471.4135861750033 <class 'numpy.float64'>
pre create h5
time: 6
[1472.35569749 1233.03825977 -151.90541188]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1472.3556974853168 <class 'numpy.float64'>
pre create h5
time: 7
[1473.29576055 1232.91979637 -152.2174792 ]
df append
df p

/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

df post append
x    float64
y    float64
z    float64
dtype: object
1600.452402442095 <class 'numpy.float64'>
pre create h5
time: 5
[1600.33276891 1702.07050325 -402.36499499]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1600.3327689059122 <class 'numpy.float64'>
pre create h5
time: 6
[1600.21012943 1702.53611244 -402.94195917]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1600.2101294263273 <class 'numpy.float64'>
pre create h5
time: 7
[1600.20835459 1702.84576066 -403.4653658 ]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1600.2083545870369 <class 'numpy.float64'>
pre create h5
time: 8
[1600.40049255 1703.44607858 -403.73181994]
df append
df post append
x    float64
y    float64
z    float64
dtype: object
1600.4004925497202 <class 'numpy.float64'>
pre create h5
time: 9
[1600.09354168 1704.27942149 -404.06551849]
df append
df post append
x    float64
y    float64
z    float64
dtype: objec

/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(my_dict, ignore_index=True)
/tmp/ipykernel_2215/2032282151.py:53: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future v

In [ ]:
file_text = f"""
<?xml version="1.0" ?>
<Xdmf xmlns:xi="http://www.w3.org/2001/XInclude" Version="2.0">
<Domain>
<Grid Name="position_{tracer_number}_{time}.h5" GridType="Uniform">

	<Time Value="{time} megayear" />

	<Topology Type="POLYVERTEX" NodesPerElement="{time+1}"> </Topology>
		<Geometry Type="XYZ">
			<DataItem Format="HDF" NumberType="Float" Precision="8" Dimensions="{time + 1} 3">position_{tracer_number}_{time}.h5:/data</DataItem>
		</Geometry>
</Grid>
</Domain>
</Xdmf>
"""

In [ ]:
h5_file_coord =  f'./my_positions/position_610.h5'

with h5py.File(h5_file_coord, 'r') as file:

            for key in file.keys():
                # create a string with the name of the var, and assign numpy value from h5
                 np_array = file[key][:] 
                    

np_array[:]
df = pd.DataFrame(np_array)
df

In [ ]:
h5_file_coord =  f'./outputs_3d_no_t_ample-moltsanys-3440-60anys/lag-5.h5'

with h5py.File(h5_file_coord, 'r') as file:

            for key in file.keys():
                # create a string with the name of the var, and assign numpy value from h5
                 np_array = file[key][:] 
                    

np_array[:]
df = pd.DataFrame(np_array)
df