In [1]:
import h5py
import pandas as pd
import numpy as np
import os
import random

### In Paraview:

    a) Open -> CSV Reader -> Apply
    
    b)Filtetr -> Alphabetical -> Table to Points
    
        x = x
        y = y 
        z = z
        
        Apply
        
        
    c) Filter -> Alphabetical -> Glyph
    
    Scalable Factor 250
    
    Apply
        

In [20]:
def create_strainrate_tensor_path(
    dir_data='./data/',
    num_particle=410
):
           #########################################
    """
    Use lag-{time} for coordinates and lag_strainratetensor
    for plotting the strainrate tensor arrow.
    """
    #########################################
    
    # Check if the data folder exists
    if not os.path.exists(dir_data):
        raise FileNotFoundError(f"Folder '{dir_data}' not found.")
    
    # count num of timesteps
    prefix = f'lag_strainratetensor'
    files = os.listdir(dir_data)
    num_files = sum([1 for file in files if file.startswith(prefix)])
    print(num_files)
    pd.set_option('display.precision', 20)
    columns = ['x', 'y', 'z', 'pr_eig_x', 'pr_eig_y', 'pr_eig_z']
    df = pd.DataFrame(columns=columns)
    
    # loop by number of files
    print('start while loop')
    time = 0
    while time < num_files:
        # velfield
        h5_file =  dir_data + f'lag_strainratetensor-{time}.h5'
            
        with h5py.File(h5_file, 'r') as file:
            for key in file.keys():
                strain_rate = file[key][num_particle]
                
                
                
        tensor = np.array([
                [strain_rate[0], strain_rate[3], strain_rate[4]],
                [strain_rate[3], strain_rate[1],strain_rate[5]],
                [strain_rate[4], strain_rate[5], strain_rate[2]]
            ])
        
        
        eigenvalues, eigenvectors = np.linalg.eigh(tensor)
        # Select the principal eigenvector (corresponding to the largest eigenvalue)
        principal_index = np.argmax(eigenvalues)
        principal_eigenvector = eigenvectors[:, principal_index]

        
        #coordinates
        h5_file_coord =  dir_data +  f'lag-{time}.h5'
        with h5py.File(h5_file_coord, 'r') as file:
            # create a variable name for storing strain rate tensor array
            for key in file.keys():
                coordinates = file[key][num_particle]
        
        # construct df row
        x = coordinates[0]
        y = coordinates[1]
        z = coordinates[2]
        pr_eig_x = principal_eigenvector[0]
        pr_eig_y = principal_eigenvector[1]
        pr_eig_z = principal_eigenvector[2]
        
        new_row = {'x': x, 'y': y, 'z': z, 'pr_eig_x': pr_eig_x, 'pr_eig_y': pr_eig_y, 'pr_eig_z': pr_eig_z}
        df = df.append(new_row, ignore_index=True)
        
        # SAVE FILE
        save_path = './strain_rate_tensor_path/'
        # Check if destination folder exist
        os.makedirs(save_path, exist_ok=True)
        df.to_csv(save_path + f'velocity_vector_{num_particle}_{time}.csv', index=False)

        time += 1

In [21]:
create_strainrate_tensor_path(dir_data='/home/jovyan/workspace/Desktop/wa/3d/no_t/outputs_3d_no_t_ample-moltsanys-3650-60anys-velocity_field_strain_rate_tensor/')

10
start while loop


/tmp/ipykernel_208/1286357430.py:67: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_208/1286357430.py:67: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_208/1286357430.py:67: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_208/1286357430.py:67: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(new_row, ignore_index=True)
/tmp/ipykernel_208/1286357430.py:67: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future versio

# Coordenades

In [3]:
h5_file_coord =  f'/home/jovyan/workspace/Desktop/wa/3d/no_t/outputs_3d_no_t_ample-moltsanys-3650-60anys-velocity_field_strain_rate_tensor/lag-5.h5'


with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name to store coord
    dataset_name = f'np_array_5'

    for key in file.keys():
        # create a string with the name of the var, and assign numpy value from h5
        globals()[dataset_name] = file[key][:] 

np_array_5[0]  

coordinates = np_array_5[0]  
coordinates

array([1404.07337971, 4997.74705993, -150.59059709])

# Strai rate tensor

In [4]:

h5_file_coord =  f'/home/jovyan/workspace/Desktop/wa/3d/no_t/outputs_3d_no_t_ample-moltsanys-3650-60anys-velocity_field_strain_rate_tensor/lag_strainratetensor-5.h5'

with h5py.File(h5_file_coord, 'r') as file:
    # create a variable name for storing strain rate tensor array
    dataset_name = f'np_array_6'

    for key in file.keys():
        dataset_name = file[key][:] 

                    
dataset_name[0]

array([ 5.5735467e-16, -1.3298003e-16,  1.5577066e-16, -3.2025191e-16,
        6.2750456e-16,  7.3679307e-17], dtype=float32)

In [5]:
strain_rate = dataset_name[0]
strain_rate

array([ 5.5735467e-16, -1.3298003e-16,  1.5577066e-16, -3.2025191e-16,
        6.2750456e-16,  7.3679307e-17], dtype=float32)

In [6]:
 tensor = np.array([
        [strain_rate[0], strain_rate[3], strain_rate[4]],
        [strain_rate[3], strain_rate[1],strain_rate[5]],
        [strain_rate[4], strain_rate[5], strain_rate[2]]
    ])

In [9]:
eigenvalues, eigenvectors = np.linalg.eigh(tensor)

In [12]:
eigenvalues, eigenvectors

(array([-4.9081970e-16,  1.5045583e-17,  1.0559194e-15], dtype=float32),
 array([[ 0.53737485, -0.22331978, -0.81323826],
        [ 0.60244304,  0.7764582 ,  0.18486497],
        [-0.59016156,  0.58927155, -0.5517866 ]], dtype=float32))

In [10]:
# Select the principal eigenvector (corresponding to the largest eigenvalue)
principal_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, principal_index]

In [11]:
principal_eigenvector

array([-0.81323826,  0.18486497, -0.5517866 ], dtype=float32)

In [14]:
principal_index

2

In [15]:
data = {
    'x': 1500,
    'y': [coordinates[0]],
    'z': [coordinates[2]],
    'pr_eig_x': [principal_eigenvector[0]],
    'pr_eig_y': [principal_eigenvector[1]],
    'pr_eig_z': [principal_eigenvector[2]]
}

df = pd.DataFrame(data)
df.head()

x           y           z  pr_eig_x  pr_eig_y  pr_eig_z
0  1500  1404.07338 -150.590597 -0.813238  0.184865 -0.551787

In [16]:
df.to_csv('strain_rate_eigenvectors.csv', index=False)